name: prestige_valet_app
description: A specialized application for providing car parking service.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #data
  connectivity_plus: ^4.0.2
  internet_connection_checker: ^1.0.0+1
  dio: ^5.3.2
  flutter_secure_storage: ^9.0.0
  barcode_scan2: ^4.2.4
  #domain
  equatable: ^2.0.5
  dartz: ^0.10.1
  #presentation
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  encrypt: ^5.0.2
  image_picker: ^1.0.4
  otp_pin_field: ^1.2.2
  lottie: ^2.7.0
  google_sign_in: ^5.4.2
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  flutter_facebook_auth: ^6.0.3
  twitter_login: ^4.4.2
  awesome_dialog: ^3.1.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/welcome_logo.png
    - images/default_user_image.jpg
    - images/splash_logo.png
    - images/Apple_Logo.png
    - images/Gmail_Logo.png
    - images/Facebook_Logo.png
    - images/Twitter_Logo.png
    - images/qr_code_scanner.json

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-Italic.ttf
        - asset: fonts/SourceSansPro-Bold.ttf
        - asset: fonts/SourceSansPro-BoldItalic.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Italic.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-BoldItalic.ttf
